[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"

[build]
  command = "yarn build"
  publish = "dist"

[functions]
  included_files = ["dist/**"]
  node_bundler = "esbuild"
  external_node_modules = ["uuid"]